(define-module (chiko-modules sets emacs)
  #:use-module (gnu)
  #:use-module (gnu home services)
  #:use-module (rosenthal)
  #:use-module (chiko-modules utils)
  #:use-module (chiko-modules loader dir-loader)
  #:use-module (chiko-modules sets)
  #:use-module (chiko-modules packages desktop)
  #:export (make-emacs))
