(define-module (chiko-modules loader set-loader)
  #:use-module (chiko-modules sets)
  #:use-module (chiko-modules utils)
  #:use-module (chiko-modules system)
  #:use-module (chiko-modules home)
  #:export (merge-sets
	    set->os-transform))

;; (define-syntax make-os-from-set
;;   (lambda (stx)
;;     (syntax-case stx ()
;;       ((_ set)
;;        (let* ((set-datum (eval (syntax->datum #'set) (interaction-environment))))
;; 	 (with-syntax (((config ...)
;; 			(datum->syntax stx (merge-config (make-os-cfg-from-set set-datum) (cfgset-sys-settings set-datum))))
;; 		       ((trans ...)
;; 			(datum->syntax stx (cfgset-sys-transforms set-datum))))
;; 	   #'(make-system (trans ...)
;; 			  (config ...))))))))

;; (define-syntax make-home-from-set
;;   (lambda (stx)
;;     (syntax-case stx ()
;;       ((_ set)
;;        (let* ((set-datum (eval (syntax->datum #'set) (interaction-environment))))
;; 	 (with-syntax (((config ...)
;; 			(datum->syntax stx (merge-config (make-home-cfg-from-set set-datum) (cfgset-home-settings set-datum))))
;; 		       ((trans ...)
;; 			(datum->syntax stx (cfgset-home-transforms set-datum))))
;; 	   #'(make-home (trans ...)
;; 			(config ...))))))))

;; (define (make-os-cfg-from-set set)
;;   (let* ((mcron-jobs (cfgset-mcron-jobs set))
;; 	 (doas-rules (cfgset-doas-rules set)))
;;     `((services ((make-mcron ,@mcron-jobs)
;; 		 (make-doas ,@doas-rules))))))

;; (define (make-home-cfg-from-set set)
;;   (let* ((home-envs (cfgset-home-envs set))
;; 	 (home-files (cfgset-home-files set))
;; 	 (home-configs (cfgset-home-configs set))
;; 	 (home-desktops (cfgset-home-desktops set))
;; 	 (home-mimes (cfgset-home-mimes set)))
;;     `((services ((make-home-env ,@home-envs)
;; 		 (make-home-files ,@home-files)
;; 		 (make-home-config ,@home-configs)
;; 		 (make-home-desktop ,@home-desktops)
;; 		 (make-home-mime ,@home-mimes))))))
